version: "3.1"

services:
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: 8CFvE52VPDhyHhcuNM2SgXm3
      POSTGRES_USER: root
      POSTGRES_DB: fathom
    volumes:
      - pgfathom:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fathom3.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgfathom:
  pgadmin-data:
