version: "3.1"

services:
  postgres-db:
    build:
      context: ./apps/db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: 8CFvE52VPDhyHhcuNM2SgXm3
      POSTGRES_USER: root
      POSTGRES_DB: fathom
    volumes:
      - pgfathom:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fathom3.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  ads-frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
  ads-api:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres-db
    environment:
      PORT: 8080
      POSTGRES_PASSWORD: 8CFvE52VPDhyHhcuNM2SgXm3
      POSTGRES_URL: postgresql://root:8CFvE52VPDhyHhcuNM2SgXm3@postgres-db:5432/fathom?schema=public
      SECRET_KEY: t5qCzzm3vTkyagrT9nKkCB8U
    ports:
      - "8080:8080"
volumes:
  pgfathom:
  pgadmin-data:
