version: "3.1"

services:
  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: 8CFvE52VPDhyHhcuNM2SgXm3
      POSTGRES_USER: root
      POSTGRES_DB: fathom
    volumes:
      - pgfathom:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgfathom:
